// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ASPCoreWebAPIDBFirst.Models;

[Keyless]
[Table("EmplyeeTest")]
public partial class EmplyeeTest
{
    public int EmployeeID { get; set; }

    [Required]
    [StringLength(10)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(20)]
    public string LastName { get; set; }

    [StringLength(15)]
    public string Country { get; set; }
}