// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ASPCoreWebAPIDBFirst.Models;

[Table("EmployeesCase")]
public partial class EmployeesCase
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal? Salary { get; set; }

    public bool? Attend { get; set; }
}