// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ASPCoreWebAPIDBFirst.Models;

[Keyless]
public partial class MonthTran
{
    public int? id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal? total { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal? Gtotal { get; set; }
}